{% set version = "0.6-3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-akima
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/akima_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/akima/akima_{{ version }}.tar.gz
  sha256: 95657592a81d2e3628cb054b60127827ae64e65c58b77d059aa510bc6781ad3e

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-sp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-sp

test:
  commands:
    - $R -e "library('akima')"           # [not win]
    - "\"%R%\" -e \"library('akima')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=akima
  license: ACM (Restricts use)
  summary: 'Several cubic spline interpolation methods of H. Akima for irregular and regular gridded data are available through this package, both for the bivariate case (irregular data: ACM 761, regular data: ACM 760) and univariate case (ACM 433 and ACM 697). Linear interpolation of irregular gridded data is also covered
    by reusing D. J. Renkas triangulation code which is part of Akimas Fortran code. A bilinear interpolator for regular grids was also added for comparison with the bicubic interpolator on regular grids.'
  license_family: OTHER
  license_file:
    - {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
