appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: crPRzasuknUL2XjTFf2+Xrd53I2QJsixXvXHI15QYmziCi/LGqzxmFuGhYnUNXs5Srg6vTGzoVuWYbnlJJkRMp6LkRRZ2cUuPfKc8+EPPWjqOZZLNyFCFzEEuqK7WO3Nekc8/TDUv2hSJXXqAl8rPwe9p9IDQ/bTLXVVSCzkyOFoHXfRXAHpAC/c5pqkD+Ql0hytM5ySJ3VfujhLx7KcNmQHSXZCoJ3OmMuwB1CUeHKEBBRqxmKPDDDBL7Zaqf5oCzmRl4SvnKzGZ30pACsILVqOJBldBBSLkj7ZbJKgLrAYOuN+NyQBoppUbtf/zvWPyI6CumtvZXAwHG6oBMiNGc45zj8hOCf2O6fnvH31uYRi24UkTkRLFZVi+j+6Cvvkz1HJuj5Z1ugAabWh+WpfwRzMRrWaV6yaTGgdfeCQeyBTVmRlgnognLR3LoZSrfrRuNdrA3v3ZE+8IbrpYPzhcvtV/yeVGEoZVLFPi02HItDmUbvBuvjp10XjaPEHNqBN5DGFsSZQRdmC5o/zUS3HC/MkckiAZy9xB3yu3llJsYR+nWPHlxeoLh+owVCW3YUqZcX4kGvxPpg2S9fzZaKwI93pJdROn5dTCUik6UdU5DipQ0fx6iYHWQiPX6QRtmhxkYm+kWty3K/kZqCqb1xCDzVvbPGFqTnbQB0jEJvLXsA=}
